# Change server port to avoid port conflict
server.port=8761

# Disable Eureka client registration and registry fetch if Eureka server is not running
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.application.name=discovery-service
